INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python04/manage.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on / [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 127.0.0.1 - - [23/May/2020 19:49:35] "GET / HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 127.0.0.1 - - [23/May/2020 19:49:36] "GET /favicon.ico HTTP/1.1" 500 -
ERROR app.py:1423 Exception on / [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 127.0.0.1 - - [23/May/2020 19:49:40] "GET / HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 127.0.0.1 - - [23/May/2020 19:49:41] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87 127.0.0.1 - - [23/May/2020 19:50:00] "GET / HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [23/May/2020 19:50:01] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [23/May/2020 19:50:27] "GET / HTTP/1.1" 404 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 14:17:11] "GET / HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 14:17:11] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 14:17:25] "GET /index HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 14:18:09] "GET /index HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 14:19:28] "GET /index HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 14:19:32] "GET /index HTTP/1.1" 404 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 14:19:45] "GET /index HTTP/1.1" 404 -
INFO _internal.py:87  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Running on http://192.168.0.106:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /index [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [24/May/2020 14:59:32] "GET /index HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [24/May/2020 14:59:33] "GET /favicon.ico HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /index [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [24/May/2020 15:00:13] "GET /index HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [24/May/2020 15:00:13] "GET /favicon.ico HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /index [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [24/May/2020 15:00:14] "GET /index HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [24/May/2020 15:00:14] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://192.168.0.106:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /index [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [24/May/2020 15:00:28] "GET /index HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [24/May/2020 15:00:28] "GET /favicon.ico HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /index [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [24/May/2020 15:01:32] "GET /index HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [24/May/2020 15:01:32] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://192.168.0.106:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /index [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [24/May/2020 15:01:55] "GET /index HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [24/May/2020 15:01:56] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /index [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [24/May/2020 15:02:26] "GET /index HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [24/May/2020 15:02:26] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /index [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [24/May/2020 15:03:21] "GET /index HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [24/May/2020 15:03:21] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:03:49] "GET /index HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:03:49] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:04:41] "GET / HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:05:39] "GET /index HTTP/1.1" 404 -
ERROR index.py:11 error msg
WARNING index.py:12 warn msg
INFO index.py:13 info msg
DEBUG index.py:14 debug msg
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:05:58] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR index.py:11 error msg
WARNING index.py:12 warn msg
INFO index.py:13 info msg
DEBUG index.py:14 debug msg
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:06:14] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR index.py:11 error msg
WARNING index.py:12 warn msg
INFO index.py:13 info msg
DEBUG index.py:14 debug msg
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:07:05] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR index.py:11 error msg
WARNING index.py:12 warn msg
INFO index.py:13 info msg
DEBUG index.py:14 debug msg
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:07:18] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR index.py:11 error msg
WARNING index.py:12 warn msg
INFO index.py:13 info msg
DEBUG index.py:14 debug msg
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:07:20] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR index.py:11 error msg
WARNING index.py:12 warn msg
INFO index.py:13 info msg
DEBUG index.py:14 debug msg
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:07:21] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:07:58] "GET /index HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:08:07] "GET /index HTTP/1.1" 404 -
ERROR index.py:11 error msg
WARNING index.py:12 warn msg
INFO index.py:13 info msg
DEBUG index.py:14 debug msg
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:08:25] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:08:38] "GET /web_html/index HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:08:52] "GET /web_html/index HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:10:33] "GET /api/v1.0/indexs HTTP/1.1" 404 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /api/v1.0/indexs [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/focusdroid/flask/ihome_python04/ihome/api_1_0/index.py", line 21, in get_index
    csrf_token = csrf.generate_csrf()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_wtf/csrf.py", line 121, in _get_config
    raise KeyError(message)
KeyError: 'A secret key is required to use CSRF.'
INFO _internal.py:87 127.0.0.1 - - [24/May/2020 15:10:51] "GET /api/v1.0/indexs HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87 127.0.0.1 - - [30/May/2020 19:15:27] "GET / HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [30/May/2020 19:15:28] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:87 127.0.0.1 - - [30/May/2020 19:16:31] "GET /api/v1.0/image_codes/1 HTTP/1.1" 200 -
INFO _internal.py:87 127.0.0.1 - - [30/May/2020 19:16:37] "GET /api/v1.0/image_codes/1 HTTP/1.1" 200 -
INFO _internal.py:87 127.0.0.1 - - [30/May/2020 19:16:45] "GET /api/v1.0/image_codes/1 HTTP/1.1" 200 -
INFO _internal.py:87 127.0.0.1 - - [30/May/2020 19:20:46] "GET /api/v1.0/image_codes/1 HTTP/1.1" 200 -
INFO _internal.py:87 127.0.0.1 - - [30/May/2020 19:21:43] "GET /api/v1.0/image_codes/1 HTTP/1.1" 200 -
INFO _internal.py:87 127.0.0.1 - - [31/May/2020 12:46:10] "GET /api/v1.0/image_codes/%EF%BC%92 HTTP/1.1" 200 -
INFO _internal.py:87 127.0.0.1 - - [31/May/2020 12:46:53] "GET /api/v1.0/image_codes/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Running on http://192.168.0.106:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /api/v1.0/image_codes/1 [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [01/Jun/2020 21:25:27] "GET /api/v1.0/image_codes/1 HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [01/Jun/2020 21:25:28] "GET /favicon.ico HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /api/v1.0/image_codes/1 [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [01/Jun/2020 21:26:13] "GET /api/v1.0/image_codes/1 HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [01/Jun/2020 21:26:13] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://192.168.0.106:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /api/v1.0/image_code/1 [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [01/Jun/2020 21:27:32] "GET /api/v1.0/image_code/1 HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [01/Jun/2020 21:27:32] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://192.168.0.106:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Running on http://192.168.0.106:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /api/v1.0/image_code/1 [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [01/Jun/2020 21:30:01] "GET /api/v1.0/image_code/1 HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [01/Jun/2020 21:30:01] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87 127.0.0.1 - - [01/Jun/2020 21:30:25] "GET /api/v1.0/image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87 127.0.0.1 - - [01/Jun/2020 21:30:25] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:87  * Running on http://192.168.0.106:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /api/v1.0/image_code/999 [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [01/Jun/2020 21:34:13] "GET /api/v1.0/image_code/999 HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [01/Jun/2020 21:34:13] "GET /favicon.ico HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /api/v1.0/image_code/999 [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [01/Jun/2020 21:34:24] "GET /api/v1.0/image_code/999 HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.106 - - [01/Jun/2020 21:34:25] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://192.168.0.106:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /api/v1.0/image_code/1 [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [01/Jun/2020 22:08:05] "GET /api/v1.0/image_code/1 HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [01/Jun/2020 22:08:05] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://192.168.0.106:5000/ (Press CTRL+C to quit)
ERROR app.py:1423 Exception on /api/v1.0/image_code/1 [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [01/Jun/2020 22:08:39] "GET /api/v1.0/image_code/1 HTTP/1.1" 500 -
ERROR app.py:1423 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/focusdroid/.virtualenvs/flask_py/lib/python2.7/site-packages/redis/connection.py", line 399, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.0.106'
INFO _internal.py:87 192.168.0.103 - - [01/Jun/2020 22:08:40] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87 127.0.0.1 - - [01/Jun/2020 22:09:08] "GET /api/v1.0/image_code/1 HTTP/1.1" 200 -
